import { ConfigService } from '@nestjs/config';
import { Repository } from 'typeorm';
import { CustomerEntity } from '../customers/entities/customer.entity';
import { ShiftEntity } from '../shifts/entities/shift.entity';
import { WaitlistEntryEntity } from '../waitlist/entities/waitlist-entry.entity';
import { AssignTableDto } from './dto/assign-table.dto';
import { CheckAvailabilityDto } from './dto/check-availability.dto';
import { CreateReservationDto } from './dto/create-reservation.dto';
import { ListReservationsQueryDto } from './dto/list-reservations.query';
import { UpdateReservationDto } from './dto/update-reservation.dto';
import { ReservationStatus } from './enums/reservation-status.enum';
import { ReservationEntity } from './entities/reservation.entity';
import { RestaurantTableEntity } from './entities/table.entity';
export declare class ReservationsService {
    private readonly reservationRepository;
    private readonly tableRepository;
    private readonly shiftRepository;
    private readonly customerRepository;
    private readonly waitlistRepository;
    private readonly configService;
    constructor(reservationRepository: Repository<ReservationEntity>, tableRepository: Repository<RestaurantTableEntity>, shiftRepository: Repository<ShiftEntity>, customerRepository: Repository<CustomerEntity>, waitlistRepository: Repository<WaitlistEntryEntity>, configService: ConfigService);
    create(createReservationDto: CreateReservationDto, createdByUserId: string): Promise<ReservationEntity>;
    list(query: ListReservationsQueryDto): Promise<ReservationEntity[]>;
    listTablesLayout(): Promise<RestaurantTableEntity[]>;
    update(id: string, updateReservationDto: UpdateReservationDto): Promise<ReservationEntity>;
    cancel(id: string, reason?: string): Promise<ReservationEntity>;
    markNoShow(id: string): Promise<ReservationEntity>;
    updateStatus(id: string, status: ReservationStatus): Promise<ReservationEntity>;
    assignTable(id: string, assignTableDto: AssignTableDto): Promise<ReservationEntity>;
    getAvailability(query: CheckAvailabilityDto): Promise<{
        shiftId: string;
        startsAt: Date;
        endsAt: Date;
        partySize: number;
        available: boolean;
        recommendedTableId: string | null;
        availableTables: Array<{
            id: string;
            tableNumber: number;
            capacity: number;
            area: string | null;
        }>;
    }>;
    private resolveReservationTiming;
    private resolveShift;
    private validateReservationWindow;
    private assertNoShowGracePeriodElapsed;
    private validateReservationAgainstShift;
    private resolveTableAssignment;
    private isTableOccupied;
    private ensureUniqueActiveCustomerShiftReservation;
    private getReservationOrThrow;
    private assertReservationIsActiveForStatusChange;
    private getShiftOrThrow;
    private ensureCustomerExists;
    private saveReservation;
    private normalizeCancellationReason;
    private saveReservationAndSyncTables;
    private syncTableAvailability;
    private getNumberConfig;
    private isPostgresConstraintError;
}
